version: '3.8'
services:
  postgres:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ${PG_DATA_PATH}:/var/lib/postgresql/data
